### ISSUE TITLE
Too many lights to display, no scrollbar

### ISSUE THREAD

**Issue by atthecarnival** [Kakifrucht/LightBeat#10]
I have so many lights, that the list of lights stretches across one line in GUI instead of wrapping. I cannot select the lights I need because there is no scrollbar to view the remaining lights that are at the end of the list. Please see attached screenshot. This is on an ultrawide monitor, if that makes a difference.

Thanks!
![LB screenshot](https://user-images.githubusercontent.com/50952685/72208194-0c8f8280-346e-11ea-81a5-907147c415d2.PNG)

**Comment by Kakifrucht** [comment]
That certainly looks bad! Thanks for reporting the issue, I see if I can finally use this as motivation to push some fixes / improvements that were long written, just never tidied up properly.

**Comment by Etrit1** [comment]
I'll add to loving to have this fixed.  I currently don't have enough lights to make it an issue but.. might in the future.

Maybe even push those fixes and improvements? :-)

**Comment by Kakifrucht** [comment]
Fixed in LightBeat v1.6.0
