### ISSUE TITLE
Question: Alternative Bridges (Open Source)

### ISSUE THREAD

**Issue by Zeroaim-exe** [Kakifrucht/LightBeat#12]
Hi i have a quick question about LightBeat.
Im planning to make 2 LED Stripes smart and i want to synch them with music. 
I dont want to buy a Philips Bridge because of privacy concerns. 
Would the following approach work?:
Connecting a ConBee II Stick to a Raspberry Pi, Installing Home Assistant or a different open source solution and then connecting LightBeat to it.

Sorry for the dumb question, im very new to the Smart home thing and dont really know anything about it.

**Comment by Zeroaim-exe** [comment]
solved my question myself. ill use diyhue as it seems to work with lightbeat.

**Comment by Kakifrucht** [comment]
Personally I haven't tested any non Philips configurations, but it should hopefully work fine with diyhue. If you had another propietary bridge then openHAB should work fine too, although at the end of the day the latency between sending light updates and executing the light change would be the relevant factor in determining if LightBeat is fun with a given configuration.
