### ISSUE TITLE
Stuck on Requesting Connection

### ISSUE THREAD

**Issue by AltEvolutions** [Kakifrucht/LightBeat#4]
I installed the Windows version, tried to pair the bridge with the app and it just got stuck at Requesting Connection, so I uninstalled it (removing the registry changes it makes too, to start 100% fresh) and ran it through the command line using java -jar Lightbeat.exe

The result is
`[Thread-3] INFO io.lightbeat.hue.bridge.HueSDKListener - Connected to bridge at 192.168.1.156 with username fvyF0RXeQZOPc2Rx4kXjfiy8ZC8xNEZTf-5alfhP`
`[Thread-0] INFO io.lightbeat.config.LBConfig - Set bridge.username to value fvyF0RXeQZOPc2Rx4kXjfiy8ZC8xNEZTf-5alfhP`
`[Thread-0] INFO io.lightbeat.config.LBConfig - Set bridge.ipaddress to value 192.168.1.156`

but it still stays stuck on Requesting Connection on the GUI, with nothing else being output.

**Comment by Kakifrucht** [comment]
I have just pushed v1.3.0 which should hopefully also fix your issue!

**Comment by AltEvolutions** [comment]
Yup, that fixed it straight away! :thumbsup:
