### ISSUE TITLE
choose an ip:port to connect to

### ISSUE THREAD

**Issue by wtf911** [Kakifrucht/LightBeat#7]
I'm running openhab with the philips hue emulator. I've noticed some hue apps can connect and others don't. In this case I'm running on port 8080 instead of port 80. It detects my bridge at 192.168.1.4 but won't connect and if i type manually 192.168.1.4:8080 it also doesn't, but other programs can. Is this something that should work or needs adding?

**Comment by Kakifrucht** [comment]
Can you try to execute LightBeat via the command line, by executing the .jar or .exe directly, like ``java -jar LightBeat.exe`` or ``java -jar LightBeat.jar`` and paste the console output? Let me know if you need further instructions to get this working.

I don't know about the API implementation the OpenHAB module is using and if it might have issues with the official (and deprecated) Philips Hue Java SDK. Non standard port should not be the issue here.

**Comment by wtf911** [comment]
I try both connecting to the one it finds 192.168.1.4 as well as manually entering 192.168.1.4:8080. This is from the output:

```
[main] INFO io.lightbeat.LightBeat - LightBeat v1.5.0 starting
Feb 05, 2019 12:02:10 AM java.util.prefs.WindowsPreferences <init>
WARNING: Could not open/create prefs root node Software\JavaSoft\Prefs at root 0x80000002. Windows RegCreateKeyEx(...) returned error code 5.
[Thread-3] INFO io.lightbeat.hue.bridge.LBHueManager - Access point scan finished, found 1 bridges
[Thread-7] ERROR io.lightbeat.hue.bridge.LBHueManager - Error ocurred, code 46 - bridge not responding
[Thread-8] INFO io.lightbeat.hue.bridge.LBHueManager - Access point scan finished, found 1 bridges
[Thread-11] ERROR io.lightbeat.hue.bridge.LBHueManager - Error ocurred, code 46 - bridge not responding
[Thread-12] INFO io.lightbeat.hue.bridge.LBHueManager - Access point scan finished, found 1 bridges
[Thread-15] ERROR io.lightbeat.hue.bridge.LBHueManager - Error ocurred, code 46 - bridge not responding
[AWT-EventQueue-0] INFO io.lightbeat.LightBeat - Shutting down LightBeat
[Thread-16] INFO io.lightbeat.hue.bridge.LBHueManager - Access point scan finished, found 1 bridges
[AWT-EventQueue-0] INFO io.lightbeat.LightBeat - Shutting down LightBeat
```

**Comment by Kakifrucht** [comment]
Thanks. Unfortunately it looks like a standard timeout with no further indication of what might have gone wrong. Can you tell me which Hue apps work with your setup, and which ones don't (preferrably open source ones, so I can check which framework they use)? 

If this is indeed an issue with the framework, there isn't much I can do about it at the moment. Migrating to the new official SDK is not really an option, as that one uses JNI and isn't platform independent anymore.

**Comment by wtf911** [comment]
Off the top of my head to following Android apps can connect to it: Hue Pro by Prismatic LLC, Huegasm, and iLightShow.

Sorry if that isn't of much help. No worries if it's not doable, thanks for taking a look.

**Comment by Kakifrucht** [comment]
Thanks, unfortunately it looks like an issue with the SDK and OpenHAB. I would definitely want to migrate away from the one we use right now, as it is also the reason LightBeat isn't open source, but alternative API's don't look that appealing to me right now. This might always change, but for now, I'm going with wontfix :/

Sorry, but thanks for taking interest in LightBeat.
