### ISSUE TITLE
Can't reconnect to an other bridge

### ISSUE THREAD

**Issue by gerolf-vent** [Kakifrucht/LightBeat#8]
Hi,
once connected to one bridge, there is no button to return to the bridge selection in the main window.
Reinstalling don't solve this, because the preferences are not cleared, when uninstalling the application.

**Comment by Kakifrucht** [comment]
Thanks for reporting. There is currently indeed no way to switch bridges, once you have connected to one. Is jumping between bridges a feature you would want to use regularly?

Adding a button to get to the bridge selection screen again is pretty straightforward to add. If you see a use case in efficiently switching between bridges, then it would make more sense for Lightbeat to store more bridge logins and allow you to reconnect without pressing the pushlink button.

If you are on Windows, you can delete the last selected bridge token by going into the registry editor and typing in the following path in the path input field: ```Computer\HKEY_CURRENT_USER\Software\JavaSoft\Prefs\io\lightbeat\config```. Delete the ``bridge.ipaddress`` and start LightBeat, it should now search for bridges again.

**Comment by Kakifrucht** [comment]
Fixed in LightBeat v1.6.0
